### ISSUE TITLE
The widget is dynamically scaled on the vertical axis so that the widget header is always visible whether or not the mobile keyboard is open.

### ISSUE THREAD

**Issue by jaX10bt** [buerokratt/Chat-Widget#343]

**Comment by IgorKrupenja** [comment]
PR with iOS fix: https://github.com/buerokratt/Chat-Widget/pull/362

To test:
- Chat looks ok and header is sticky on both iOS and Android.
- Scrolling works correctly in chat if there are messages that do not fit in the viewport.

**Comment by jaX10bt** [comment]
Widget header does not go off the screen when keypad is opened, but scrolling up or down will make the widget header not sticky.

Tested on iOS in a client's environment:
https://github.com/user-attachments/assets/7f564a10-d6c3-4515-b1c5-baf6d7698bed

**Comment by jaX10bt** [comment]
Will have to be retested on prod environment

**Comment by IgorKrupenja** [comment]
@jaX10bt FYI: unassigning, there is nothing left to do for me here at the moment.

**Comment by IgorKrupenja** [comment]
Related PR: https://github.com/buerokratt/Chat-Widget/pull/421

Please test the three points below **on both iOS and Android**:

1. Widget closed:
	a. Scrolling on the page with the widget works without issues.
2. Widget open **but** on-screen keyboard is **not** open:
	a. Scrolling of messages in chat works.
	b. There are no redundant scrollbars that scroll the page beneath the widget.
3. Widget open **and** on-screen keyboard is **open**:
	a. Scrolling of messages in chat works.
	b. There are no redundant scrollbars that scroll the page beneath the widget.
	c. It is not possible to scroll so that widget window is resized, header becomes not sticky or similar.

Please also test this in a **desktop** browser:

4. Scrolling on the page with the widget works without issues, both with widget closed and open.

**Comment by ruudel** [comment]
Tested on iOS and Android

Widget closed:
a. Scrolling on the page with the widget works without issues. :heavy_check_mark:

Widget open but on-screen keyboard is not open:
a. Scrolling of messages in chat works. :heavy_check_mark:
b. There are no redundant scrollbars that scroll the page beneath the widget. :heavy_check_mark:

Widget open and on-screen keyboard is open: 
a. Scrolling of messages in chat works. :heavy_check_mark:
b. There are no redundant scrollbars that scroll the page beneath the widget. :heavy_check_mark:
c. It is not possible to scroll so that widget window is resized, header becomes not sticky or similar. ❌

Can this be considered as not sticky? When the user scrolls up:
https://github.com/user-attachments/assets/92bdb5d2-9fd6-49c2-b155-68b72212ad00

New bug:
The widget goes out of view in landscape mode. 

![Image](https://github.com/user-attachments/assets/3e37fc24-ad14-423d-a9c4-05c517754e00)

**Comment by IgorKrupenja** [comment]
The header and general weirdness around scrolling with keyboard open on iOS have been fixed in this PR: https://github.com/buerokratt/Chat-Widget/pull/452

The rotation issue is not related to this bug, please create a separate bug for this and we can take it later.

**Comment by IgorKrupenja** [comment]
Technical note: this is just a workaround for [an iOS bug](https://stackoverflow.com/questions/56351216/ios-safari-unwanted-scroll-when-keyboard-is-opened-and-body-scroll-is-disabled).

**Comment by ruudel** [comment]
Still an issue on iOS
Tested on iPhone Pro Max 15
iOS / Safari version 18.4.1

https://github.com/user-attachments/assets/0e327818-f588-4204-a78e-0d177dc9c630

**Comment by IgorKrupenja** [comment]
Honestly, I do not think there is anything left to fix here and the current behaviour in the video is expected. If the widget is scrolled to the top already and the user drags the widget further, the widget will move together with the page body. Then:

- At some point, this will trigger the page refresh. After refresh the widget is correctly closed.
- **OR**, if the user lifts his finger before refresh, the body along with the widget header will return back into original position.

**Comment by rasmusei** [comment]
Works as intended
